In [7]:
import plotly.express as px
import pandas as pd
import json

In [61]:
with open ("ml_zoomcamp_metadata.json", "r") as f:
    metadata = json.load(f)

dat = []
for i in metadata:
    dat.append(
        {"id": i["id"],
        "title": i["title"],
        "duration": i["duration"],
        "view_count": i["view_count"]}

    )

df = pd.DataFrame(dat)

# clean title
remove_phrases = ["ML Zoomcamp 2025", "ML Zoomcamp "]
for i in remove_phrases:
    df["cleaned_title"] = df["title"].str.replace(i, "", regex=False)

# separate by modules
df["module"] = df["cleaned_title"].str.extract(r"^(\d+)")

# fix the first two modules
df.loc[[0, 1], "module"] = ["0", "0"]

# replace NaN - the kubernetes video with 100
df["module"] = df["module"].fillna(11)

# change module column into int
df["module"] = df["module"].astype(int)
df.head(5)

,id,title,duration,view_count,cleaned_title,module
0,z064DoidiKg,ML Zoomcamp 2025 Launch | Free Machine Learnin...,4730,21000,2025 Launch | Free Machine Learning Course Ove...,0
1,ph1PxZIkz1o,ML Zoomcamp 2025 Pre-Course Live Q&A | Free Ma...,3695,6100,2025 Pre-Course Live Q&A | Free Machine Learni...,0
2,Crm_5n4mvmg,ML Zoomcamp 1.1 - Introduction to Machine Lear...,577,45000,1.1 - Introduction to Machine Learning,1
3,CeukwyUdaz8,ML Zoomcamp 1.2 - ML vs Rule-Based Systems,1048,26000,1.2 - ML vs Rule-Based Systems,1
4,j9kcEuGcC2Y,ML Zoomcamp 1.3 - Supervised Machine Learning,1173,20000,1.3 - Supervised Machine Learning,1

In [62]:
df.tail()

,id,title,duration,view_count,cleaned_title,module
92,UjVkpszDzgk,ML Zoomcamp 10.5 - Introduction to Kubernetes,608,2700,10.5 - Introduction to Kubernetes,10
93,PPUCVRIV9t8,ML Zoomcamp 10.6 - Deploying a Simple Service ...,1829,3000,10.6 - Deploying a Simple Service to Kubernetes,10
94,6vHLMdnjO2w,ML Zoomcamp 10.7 - Deploying TensorFlow Models...,1481,2000,10.7 - Deploying TensorFlow Models to Kubernetes,10
95,89jxeddZtC0,ML Zoomcamp 10.8 - Deploying to EKS,1115,1600,10.8 - Deploying to EKS,10
96,J5LMRTIu4jY,ML Zoomcamp 10.9 - Summary,509,978,10.9 - Summary,10

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             97 non-null     str
 1   title          97 non-null     str
 2   duration       97 non-null     int64
 3   view_count     97 non-null     int64
 4   cleaned_title  97 non-null     str
 5   module         97 non-null     int64
dtypes: int64(3), str(3)
memory usage: 4.7 KB

In [ ]:
# # test location
# print(df.loc[2, "module"])

1

In [82]:
duration = px.box(
    data_frame=df, 
    x="module",
    y="duration",
    color="module",
    hover_name="title"
)
duration.show()

In [80]:
view_count = px.box(
    data_frame=df,
    x="module",
    y="view_count",
    color="module",
    hover_name="title",
)
view_count.show()

In [79]:
corr = px.scatter(
    data_frame=df,
    x="duration",
    y="view_count",
    hover_name="title",
    hover_data={
        "duration": True,
        "view_count": True,
        "title": False
    }
)
corr.show()